%%{init: {"themeVariables": {"fontSize": "15px", "nodeSpacing": 40, "rankSpacing": 100}}}%%
graph LR
    A[Archivio dei Contenuti] --> B[Motore AI]
    B --> C[Modulo Leitner]
    C --> D{Previsione Dimenticanze}
    D --> E[(Salva Risultati)]
    B --> F[Pianificatore Sprint]
    F --> G[Dashboard Curva di Crescita]
    G --> H[Analisi dei Progressi]
    H --> I[App Mobile]
    H -->|Feedback| B
